
import os, json

OPENAI_API_KEY=os.getenv("OPENAI_API_KEY")
OPENAI_ASSISTANT_ID=os.getenv("OPENAI_ASSISTANT_ID")
GOOGLE_SERVICE_ACCOUNT_JSON=os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")

CAL_POLIMENTOS_ID=os.getenv("CAL_POLIMENTOS_ID")
CAL_HIGIENIZACAO_ID=os.getenv("CAL_HIGIENIZACAO_ID")
CAL_LAVAGENS_ID=os.getenv("CAL_LAVAGENS_ID")
CAL_PELICULAS_ID=os.getenv("CAL_PELICULAS_ID")
CAL_INSTALACOES_ID=os.getenv("CAL_INSTALACOES_ID")
CAL_MARTELINHO_ID=os.getenv("CAL_MARTELINHO_ID")
CAL_ROLE_GUARULHOS_ID=os.getenv("CAL_ROLE_GUARULHOS_ID")

def get_service_account():
    return json.loads(GOOGLE_SERVICE_ACCOUNT_JSON)
